name: "Pronto Action"
description: "Github action of Pronto"
author: "HeRoMo/Mac Chiang"
branding:
  icon: "code"
  color: "blue"
inputs:
  github_token:
    description: "GITHUB_TOKEN."
    required: false
    default: ${{ github.token }}
  commit:
    description: "Commit for the diff."
    required: false
    default: "origin/${{ github.base_ref }}"
  runner:
    description: "Run only the passed runners."
    required: false
    default: "standardrb brakeman"
  formatters:
    description: "Pick output formatters."
    required: false
    default: "github_status github_pr_review"
  path:
    description: "Relative path to check"
    required: false
    default: "."
runs:
  using: "docker"
  image: docker://ghcr.io/easyship/pronto-action:v3
  entrypoint: "/pronto/entrypoint.sh"
